name: gh-pages-deploy
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          version:  14.x

      - name: Clean install dependencies
        run: yarn install

      - name: Run deploy script
        run: |
          git config user.name "Dedal378" && git config user.email "orlovetsjob@gmail.com"
          yarn deploy
